apps/barriers/urls.py
from django.urls import path

from .views import (
    BarrierDetailsView,
    BarriersListView,
    FindActiveBarriers,
    FindBarriersSplashView,
    FindResolvedBarriers,
    LocationFiltersView,
    SectorFiltersView,
)

app_name = "barriers"

urlpatterns = [
    path("", FindBarriersSplashView.as_view(), name="find-barriers-splash"),
    path("active/", FindActiveBarriers.as_view(), name="find-active-barriers"),
    path("resolved/", FindResolvedBarriers.as_view(), name="find-resolved-barriers"),
    path("location/", LocationFiltersView.as_view(), name="choose-location"),
    path("sector/", SectorFiltersView.as_view(), name="choose-sector"),
    path("barriers/", BarriersListView.as_view(), name="list"),
    path("barriers/<barrier_id>/", BarrierDetailsView.as_view(), name="details"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from apps.pingdom.urls import urlpatterns as pingdom_urlpatterns

urlpatterns = []

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    if settings.DJANGO_ENV == "local":
        urlpatterns += [
            path("admin/", admin.site.urls),
        ]

    # If debug toolbar is installed
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    # Expose static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("", include("apps.barriers.urls", namespace="barriers")),
    path("", include("apps.core.urls", namespace="core")),
    path("", include("apps.feedback.urls", namespace="feedback")),
    path("", include("apps.healthcheck.urls", namespace="healthcheck")),
] + pingdom_urlpatterns

apps/barriers/views.py
from django.urls import reverse
from django.views.generic import TemplateView

from apps.core.api_client import data_gateway
from apps.core.mixins import BreadcrumbsMixin
from apps.metadata.aggregators import (
    AllLocations,
    AllSectors,
    countries,
    sectors,
    trading_blocs,
)


class BarriersListMixin:
    _barriers = None

    def get_sort_field(self):
        """
        Get sort field based on filters currently applied:

                       -------------Location-------------
                       |___None___|__Value___|___All____|
               | None  | location | sectors  | location |
        Sector | Value | location | location | location |
               | All   | location | sectors  | location |
        """
        if self.request.location is not None and not isinstance(
            self.request.location, AllLocations
        ):
            if self.request.sector is None or isinstance(
                self.request.sector, AllSectors
            ):
                return "sectors"
        return "location"

    def get_barriers_list(self):
        if not self._barriers:
            filters = {
                "location": self.request.location,
                "sector": self.request.sector,
                "is_resolved": self.request.resolved,
            }
            self._barriers = data_gateway.barriers_list(
                filters=filters,
                sort_by=self.get_sort_field(),
                headers=self.request.zipkin_http_headers,
            )
        return self._barriers

    def get_visible_groups(self, groups):
        """
        Helper to list the group letters that have records and so it's easier to
        show/hide them in the templates. (i.e on the sector/location pages)
        """
        visible_groups = []
        for k, v in groups.items():
            items_with_records = [item for item in v if item.records_count]
            if items_with_records:
                visible_groups.append(k)
        return visible_groups


class FindBarriersSplashView(TemplateView):
    template_name = "barriers/find_barriers_splash.html"
    extra_context = {
        "title": "What are you looking for?",
    }


class FindActiveBarriers(BreadcrumbsMixin, TemplateView):
    template_name = "barriers/find_active_barriers.html"
    breadcrumbs = (("Find trade barriers", None),)
    extra_context = {
        "title": "Find trade barriers",
    }


class FindResolvedBarriers(BreadcrumbsMixin, TemplateView):
    template_name = "barriers/find_resolved_barriers.html"
    breadcrumbs = (("Find resolved trade barriers", None),)
    extra_context = {
        "title": "Find resolved trade barriers",
    }


class LocationFiltersView(BreadcrumbsMixin, BarriersListMixin, TemplateView):
    template_name = "barriers/choose_location.html"

    def get_breadcrumbs(self):
        if self.request.resolved:
            return (
                (
                    "Find resolved trade barriers",
                    reverse("barriers:find-resolved-barriers"),
                ),
                ("Choose a location", None),
            )
        return (
            ("Find trade barriers", reverse("barriers:find-active-barriers")),
            ("Choose a location", None),
        )

    def get_trading_blocs(self):
        barriers = self.get_barriers_list()
        choices = trading_blocs.count_records("trading_bloc", barriers["all"])
        return choices

    def get_countries(self):
        barriers = self.get_barriers_list()
        choices = countries.count_records("country", barriers["all"])
        return choices

    def get_caption(self):
        caption = ""
        if self.request.sector:
            caption = f"in {self.request.sector.name}"
        return caption

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["trading_blocs"] = self.get_trading_blocs()
        context["trading_blocs_with_records"] = self.get_visible_groups(
            context["trading_blocs"]
        )
        context["countries"] = self.get_countries()
        context["countries_with_records"] = self.get_visible_groups(
            context["countries"]
        )
        context["title"] = "Choose a location"
        context["caption"] = self.get_caption()
        context["resolved"] = self.request.resolved
        return context


class SectorFiltersView(BreadcrumbsMixin, BarriersListMixin, TemplateView):
    template_name = "barriers/choose_sector.html"

    def get_breadcrumbs(self):
        if self.request.resolved:
            return (
                (
                    "Find resolved trade barriers",
                    reverse("barriers:find-resolved-barriers"),
                ),
                ("Choose a sector", None),
            )
        return (
            ("Find trade barriers", reverse("barriers:find-active-barriers")),
            ("Choose a sector", None),
        )

    def get_sectors(self):
        barriers = self.get_barriers_list()
        data = list(barriers["all"])
        all_sectors_count = len([b for b in data if b.sectors == AllSectors.name])
        choices = sectors.count_records(
            "sectors", data, op="include", offset=all_sectors_count
        )
        return choices

    def get_caption(self):
        caption = ""
        if self.request.location:
            caption = f"in {self.request.location.name}"
        return caption

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sectors"] = self.get_sectors()
        context["sectors_with_records"] = self.get_visible_groups(context["sectors"])
        context["title"] = "Choose a sector"
        context["caption"] = self.get_caption()
        return context


class BarriersListView(BreadcrumbsMixin, BarriersListMixin, TemplateView):
    template_name = "barriers/list.html"

    def get_title(self, location=None):
        if self.request.resolved:
            title = "Resolved trade barriers"
        else:
            title = "Trade barriers"
        if location and location != "all":
            title += f" in {location}"
        return title

    def get_breadcrumbs(self):
        if self.request.resolved:
            return (
                (
                    "Find resolved trade barriers",
                    reverse("barriers:find-resolved-barriers"),
                ),
                ("Resolved trade barriers", None),
            )
        return (
            ("Find trade barriers", reverse("barriers:find-active-barriers")),
            ("Trade barriers", None),
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["barriers"] = self.get_barriers_list()
        context["title"] = self.get_title(self.request.location)
        return context


class BarrierDetailsView(BreadcrumbsMixin, TemplateView):
    template_name = "barriers/details.html"
    barrier = None

    def get(self, request, *args, **kwargs):
        self.barrier = data_gateway.barrier_details(
            id=self.kwargs["barrier_id"],
            headers=self.request.zipkin_http_headers,
        )
        return super().get(request, *args, **kwargs)

    def get_breadcrumbs(self):
        if self.request.resolved:
            return (
                (
                    "Find resolved trade barriers",
                    reverse("barriers:find-resolved-barriers"),
                ),
                (
                    "Resolved trade barriers",
                    reverse("barriers:list") + f"?{self.request.query_string}",
                ),
                (self.barrier.title, None),
            )
        return (
            ("Find trade barriers", reverse("barriers:find-active-barriers")),
            (
                "Trade barriers",
                reverse("barriers:list") + f"?{self.request.query_string}",
            ),
            (self.barrier.title, None),
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.barrier.title
        context["barrier"] = self.barrier
        return context

apps/templates/barriers/choose_location.html
{% extends 'base.html' %}
{% load breadcrumbs %}
{% load headers %}
{% load query_params %}
{% block page_title %}{{ title }} - {{ block.super }}{% endblock %}

{% block page_content %}
    {% content_header title caption below=True %}

    <p class="govuk-body">
        <a href="{% url "barriers:list" %}{% location_filter "all" %}" class="govuk-link govuk-!-font-weight-bold">
            Select all locations
        </a>
    </p>

    {% if countries_with_records %}
    <h2 class="govuk-!-margin-bottom-0">Countries and territories</h2>
    <span class="govuk-caption-m govuk-!-margin-bottom-1">
        Countries and territories with no results are hidden, brackets show the number of issues.
    </span>
    <div class="filter-options__container">
        {% for initial_letter, country_list in countries.items %}
            {% if initial_letter in countries_with_records %}
            <div class="filter-options-group__container">
                <h3>{{ initial_letter }}</h3>
                {% for country in country_list %}
                    <p class="govuk-body">
                        {% if country.records_count %}
                            <a href="{% url "barriers:list" %}{% location_filter country.slug %}"
                               class="govuk-link country__item">
                                {{ country.name }} ({{ country.records_count }})
                            </a>
                        {% else %}
{#                            TODO: Hide until there's a toggle to show options without records#}
{#                            <a href="{% url "barriers:list" %}{% location_filter country.slug %}"#}
{#                               class="govuk-link govuk-link--muted govuk-link">#}
{#                                {{ country.name }}#}
{#                            </a>#}
                        {% endif %}
                    </p>
                {% endfor %}
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}

    {% if trading_blocs_with_records %}
    <h2 class="govuk-!-margin-bottom-0">Trading bloc</h2>
    <span class="govuk-caption-m govuk-!-margin-bottom-4">Trading blocs with no results are hidden, brackets show the number of issues.</span>
    <div class="filter-options__container">
        {% for initial_letter, trading_blocs_list in trading_blocs.items %}
            {% if initial_letter in trading_blocs_with_records %}
            <div class="filter-options-group__container">
                {% for trading_bloc in trading_blocs_list %}
                    <p class="govuk-body">
                    {% if trading_bloc.records_count %}
                        <a href="{% url "barriers:list" %}{% location_filter trading_bloc.slug %}"
                           class="govuk-link trading-bloc__item">
                            {{ trading_bloc.name }} ({{ trading_bloc.records_count }})
                        </a>
                    {% else %}
{#                        TODO: Hide until there's a toggle to show options without records#}
{#                        <a href="{% url "barriers:list" %}{% location_filter trading_bloc.slug %}"#}
{#                           class="govuk-link govuk-link--muted">#}
{#                            {{ trading_bloc.name }}#}
{#                        </a>#}
                    {% endif %}
                    </p>
                {% endfor %}
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}

{% endblock %}

apps/templates/barriers/choose_sector.html
{% extends 'base.html' %}
{% load breadcrumbs %}
{% load headers %}
{% load query_params %}
{% block page_title %}{{ title }} - {{ block.super }}{% endblock %}

{% block page_content %}
    {% content_header title caption below=True %}

    <p class="govuk-body">
        <a href="{% url "barriers:list" %}{% sector_filter "all" %}" class="govuk-link govuk-!-font-weight-bold">
            Select all sectors
        </a>
    </p>

    {% if sectors_with_records %}
    <h2 class="govuk-!-margin-bottom-0">Sector</h2>
    <span class="govuk-caption-m govuk-!-margin-bottom-1">Sectors with no results are hidden, brackets show the number of issues.</span>
    <div class="filter-options__container">
        {% for initial_letter, sector_list in sectors.items %}
            {% if initial_letter in sectors_with_records %}
            <div class="filter-options-group__container">
                <h3>{{ initial_letter }}</h3>
                {% for sector in sector_list %}
                    <p class="govuk-body">
                        {% if sector.records_count %}
                            <a href="{% url "barriers:list" %}{% sector_filter sector.slug %}"
                               class="govuk-link sector__item">
                                {{ sector.name }} ({{ sector.records_count }})
                            </a>
                        {% else %}
{#                            TODO: Hide until there's a toggle to show options without records#}
{#                            <a href="{% url "barriers:list" %}{% sector_filter sector.slug %}"#}
{#                               class="govuk-link govuk-link--muted">#}
{#                                {{ sector.name }}#}
{#                            </a>#}
                        {% endif %}
                    </p>
                {% endfor %}
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}

{% endblock %}

apps/templates/barriers/details.html
{% extends 'base.html' %}
{% load breadcrumbs %}
{% load headers %}
{% load query_params %}

{% block page_title %}{{ barrier.title }} - {{ block.super }}{% endblock %}

{% block page_content %}

    <section>
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">
                <div class="govuk-notification-banner" role="region" aria-labelledby="govuk-notification-banner-title"
                     data-module="govuk-notification-banner">
                    <div class="govuk-notification-banner__header">
                        <h4 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
                            Information
                        </h4>
                    </div>
                    <div class="govuk-notification-banner__content">
                        <p class="govuk-body">
                            This barrier is unrelated to the end of the transition period, following the United Kingdom's
                            departure from the EU.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="govuk-!-margin-bottom-9">

        <span class="govuk-caption-m">Public ID: {{ barrier.public_id }}</span>
        <h1 class="govuk-heading-xl govuk-!-margin-bottom-1">{{ barrier.title }}</h1>
        <span class="govuk-caption-s">in {{ barrier.simple_location }}</span>

    </section>

    <section class="govuk-!-margin-bottom-9">
        <!-- Summary -->
        <h2 class="govuk-heading-m">Trade barrier summary</h2>
        <p class="govuk-body field-value">{{ barrier.summary|linebreaksbr }}</p>
        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

        <!-- Sectors -->
        <h2 class="govuk-heading-s field-heading">Sectors affected</h2>
        <ul class="govuk-list govuk-list--bullet field-value">
            {% for sector in barrier.sectors_list %}
                <li>{{ sector }}</li>
            {% endfor %}
        </ul>
        {# Remove Category field until further notice #}
        {# ========================================================================================   #}
        {#        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">#}
        {#        <!-- Category -->#}
        {#        <h2 class="govuk-heading-s field-heading">Categories</h2>#}
        {#        <ul class="govuk-list govuk-list--bullet field-value">#}
        {#        {% for category in barrier.categories_list %}#}
        {#            <li>{{ category }}</li>#}
        {#        {% endfor %}#}
        {#        </ul>#}
        {# ========================================================================================   #}
        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">
        <!-- Status -->
        <h2 class="govuk-heading-s field-heading">Resolved</h2>
        <p class="govuk-body field-value">{{ barrier.is_resolved_text }}</p>
        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

        <h2 class="govuk-heading-s field-heading">Date reported</h2>
        <p class="govuk-body field-value">{{ barrier.reported_on|date:"j F Y" }}</p>
        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

        <h2 class="govuk-heading-s field-heading">Last updated</h2>
        <p class="govuk-body field-value">{{ barrier.last_published_on|date:"j F Y" }}</p>
        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">

        <h2 class="govuk-heading-s field-heading">Public ID</h2>
        <p class="govuk-body field-value">{{ barrier.public_id }}</p>
        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">
    </section>

    <section>
        <a href="{% url "barriers:list" %}{% remove_filter "nada" %}" role="button" draggable="false"
           class="govuk-button back-to-search-results__button" data-module="govuk-button">
            Back to search results
        </a>
    </section>

    <section>
        {% include "partials/additional_links.html" %}
    </section>

{% endblock %}

apps/templates/barriers/find_active_barriers.html
{% extends 'base.html' %}
{% load headers %}

{% block page_title %}{{ title }} - {{ block.super }}{% endblock %}

{% block page_content %}
    {% content_header title %}
    <div>
        <p class="govuk-body govuk-!-font-weight-bold">
            <a href="{% url 'barriers:choose-location' %}?resolved=0" class="govuk-link">
                Find trade barriers by location
            </a>
        </p>
        <p class="govuk-body">or</p>
        <p class="govuk-body govuk-!-font-weight-bold">
            <a href="{% url 'barriers:choose-sector' %}?resolved=0" class="govuk-link">
                Find trade barriers by sector
            </a>
        </p>
    </div>
{% endblock %}

apps/templates/barriers/find_barriers_splash.html
{% extends 'base.html' %}
{% load headers %}

{% block page_title %}{{ title }} - {{ block.super }}{% endblock %}

{% block page_content %}
    {% content_header title %}
    <div>
        <div class="container govuk-!-margin-bottom-7">
            <div class="govuk-grid-row">
                <div class="govuk-grid-column-two-thirds">
                    <p class="govuk-body govuk-!-font-weight-bold">
                        <a href="{% url 'barriers:find-active-barriers' %}" class="govuk-link">
                            Trade barriers
                        </a>
                    </p>
                    <p class="govuk-body">
                        Current issues that may impact your business by adding extra costs or delays, they may even stop
                        you
                        trading or investing overseas.
                    </p>
                </div>
            </div>

            <p class="govuk-body">or</p>

            <div class="govuk-grid-row">
                <div class="govuk-grid-column-two-thirds">
                    <p class="govuk-body govuk-!-font-weight-bold">
                        <a href="{% url 'barriers:find-resolved-barriers' %}" class="govuk-link">
                            Resolved trade barriers
                        </a>
                    </p>
                    <p class="govuk-body">
                        Resolved issues which may give insight in dealing with your chosen market.
                    </p>
                </div>
            </div>
        </div>

        <div class="disclaimer">
            <p class="govuk-body">
                This is not a complete list of reported trade barriers, as not all are suitable for publication. If a
                trade barrier is affecting your exports or investment from the UK, please let us know on
                <a class="govuk-link" href="https://www.great.gov.uk/report-trade-barrier/" target="_blank">
                    report a trade barrier
                </a>. Newly reported trade barriers will not appear immediately as they need to be reviewed.</p>
        </div>
    </div>
{% endblock %}

apps/templates/barriers/find_resolved_barriers.html
{% extends 'base.html' %}
{% load headers %}

{% block page_title %}{{ title }} - {{ block.super }}{% endblock %}

{% block page_content %}
    {% content_header title %}
    <div>
        <p class="govuk-body govuk-!-font-weight-bold">
            <a href="{% url 'barriers:choose-location' %}?resolved=1" class="govuk-link">
                Find resolved trade barriers by location
            </a>
        </p>
        <p class="govuk-body">or</p>
        <p class="govuk-body govuk-!-font-weight-bold">
            <a href="{% url 'barriers:choose-sector' %}?resolved=1" class="govuk-link">
                Find resolved trade barriers by sector
            </a>
        </p>
    </div>
{% endblock %}

apps/templates/barriers/list.html
{% extends 'base.html' %}
{% load breadcrumbs %}
{% load headers %}
{% load query_params %}

{% block page_title %}Search results - {{ block.super }}{% endblock %}

{% block page_content %}

    {% content_header title %}

    <section class="restrict-width">
        <dl class="govuk-summary-list search-filters">
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Location
                </dt>
                <dd class="govuk-summary-list__value">
                    <a href="{% url "barriers:choose-location" %}{% remove_filter "location" %}" class="govuk-link">
                    {% if location %}
                        {{ location.name }}
                    {% else %}
                        Filter by location
                    {% endif %}
                    </a>
                </dd>
                <dd class="govuk-summary-list__actions">
                {% if location %}
                    <a href="{% url "barriers:list" %}{% remove_filter "location" %}" class="govuk-link">
                        Clear<span class="govuk-visually-hidden"> location</span>
                    </a>
                {% endif %}
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Sector
                </dt>
                <dd class="govuk-summary-list__value">
                    <a href="{% url "barriers:choose-sector" %}{% remove_filter "sector" %}" class="govuk-link">
                    {% if sector %}
                        {{ sector.name }}
                    {% else %}
                        Filter by sector
                    {% endif %}
                    </a>
                </dd>
                <dd class="govuk-summary-list__actions">
                    {% if sector %}
                    <a href="{% url "barriers:list" %}{% remove_filter "sector" %}" class="govuk-link">
                        Clear<span class="govuk-visually-hidden"> sector</span>
                    </a>
                    {% endif %}
                </dd>
            </div>
        </dl>
    </section>

    <section>
        <div class="filter-results-header">
            <div class="filter-results-header__row">
                <div class="filter-results-count__container">
                    <h2 class="filter-results-title">
                        {{ barriers.count }}
                        <span class="filter-results-title__caption"> result{{ barriers.count|pluralize }} found</span>
                    </h2>
                </div>
            </div>
        </div>
        {% if barriers.count %}
        <table class="govuk-table filter-results-table">
            <thead class="govuk-table__head">
            <tr class="govuk-table__row">
                <th scope="col" class="govuk-table__header">Title</th>
                <th scope="col" class="govuk-table__header">Sector</th>
                <th scope="col" class="govuk-table__header">Location</th>
                {% if request.resolved %}
                    <th scope="col" class="govuk-table__header">Resolved date</th>
                {% endif %}
            </tr>
            </thead>
            <tbody class="govuk-table__body">
            {% for barrier in barriers.all %}
                <tr class="govuk-table__row">
                    <td class="govuk-table__cell">
                        <a href="{% url "barriers:details" barrier.id %}{% remove_filter "nada" %}"
                           class="govuk-link barrier__item">
                            {{ barrier.title }}
                        </a>
                    </td>
                    <td class="govuk-table__cell">{{ barrier.sectors }}</td>
                    <td class="govuk-table__cell">{{ barrier.simple_location }}</td>
                    {% if request.resolved %}
                        <td class="govuk-table__cell">
                            {% if barrier.is_resolved and barrier.status_date %}
                                {{ barrier.status_date|date:"F Y" }}
                            {% endif %}
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h2 class="filter-results-comment">
            There are no results for your search.
        </h2>
        {% endif %}
    </section>

    <section>
        {% include "partials/additional_links.html" %}
        {% if request.resolved is True %}
            <p class="govuk-body">
                <a class="govuk-link" href="{% url 'barriers:find-barriers-splash' %}">Active trade barriers</a> are
                listed separately.
            </p>
        {% elif request.resolved is False %}
            <p class="govuk-body"><a class="govuk-link" href="{% url 'barriers:find-barriers-splash' %}">Resolved trade
                barriers</a> are listed separately.</p>
        {% endif %}
    </section>

{% endblock %}