apps/barriers/urls.py
from django.urls import path

from .views import (
    BarrierDetailsView,
    BarriersListView,
    FindActiveBarriers,
    FindBarriersSplashView,
    FindResolvedBarriers,
    LocationFiltersView,
    SectorFiltersView,
)

app_name = "barriers"

urlpatterns = [
    path("", FindBarriersSplashView.as_view(), name="find-barriers-splash"),
    path("active/", FindActiveBarriers.as_view(), name="find-active-barriers"),
    path("resolved/", FindResolvedBarriers.as_view(), name="find-resolved-barriers"),
    path("location/", LocationFiltersView.as_view(), name="choose-location"),
    path("sector/", SectorFiltersView.as_view(), name="choose-sector"),
    path("barriers/", BarriersListView.as_view(), name="list"),
    path("barriers/<barrier_id>/", BarrierDetailsView.as_view(), name="details"),
]

apps/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import CookiePolicyView, CookiesView

app_name = "core"

urlpatterns = [
    path("cookies/", CookiesView.as_view(), name="cookies"),
    path("cookie-policy/", CookiePolicyView.as_view(), name="cookie-policy"),
    path(
        "accessibility/",
        TemplateView.as_view(template_name="pages/accessibility.html"),
        name="accessibility",
    ),
    path(
        "disclaimer/",
        TemplateView.as_view(template_name="pages/disclaimer.html"),
        name="disclaimer",
    ),
]

apps/feedback/urls.py
from django.urls import path

from .views import (
    FeedbackBarrierView,
    FeedbackIssueView,
    FeedbackSplashView,
    FeedbackThankYouView,
    FeedbackUsabilityView,
)

app_name = "feedback"

urlpatterns = [
    path("feedback/", FeedbackSplashView.as_view(), name="splash"),
    path("feedback/barrier/", FeedbackBarrierView.as_view(), name="barrier"),
    path("feedback/issue/", FeedbackIssueView.as_view(), name="issue"),
    path("feedback/usability/", FeedbackUsabilityView.as_view(), name="usability"),
    path("feedback/thank-you/", FeedbackThankYouView.as_view(), name="thank-you"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from apps.pingdom.urls import urlpatterns as pingdom_urlpatterns

urlpatterns = []

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    if settings.DJANGO_ENV == "local":
        urlpatterns += [
            path("admin/", admin.site.urls),
        ]

    # If debug toolbar is installed
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    # Expose static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("", include("apps.barriers.urls", namespace="barriers")),
    path("", include("apps.core.urls", namespace="core")),
    path("", include("apps.feedback.urls", namespace="feedback")),
    path("", include("apps.healthcheck.urls", namespace="healthcheck")),
] + pingdom_urlpatterns

apps/templates/partials/additional_links.html
<p class="govuk-body">
    If a trade barrier is affecting your exports or investment from the UK, please let us know on
    <a class="govuk-link" href="https://www.great.gov.uk/report-trade-barrier/" target="_blank">
        report a trade barrier
    </a>.
</p>

<p class="govuk-body">
    If you export goods you can
    <a class="govuk-link" href="https://www.gov.uk/check-duties-customs-exporting" target="_blank">
        check duties and customs procedures
    </a> for your chosen market.
</p>

apps/templates/partials/breadcrumbs.html
<div class="govuk-breadcrumbs govuk-width-container">
    <ol class="govuk-breadcrumbs__list">
        {% for crumb in breadcrumbs %}
        <li class="govuk-breadcrumbs__list-item{{ crumb.css_classes }}">
            {% if crumb.href %}
                <a class="govuk-breadcrumbs__link" href="{{ crumb.href }}">{{ crumb.text }}</a>
            {% else %}
                {{ crumb.text }}
            {% endif %}
        </li>
        {% endfor %}
    </ol>
</div>

apps/templates/partials/content_header.html
<div class="govuk-grid-row">
    <div class="govuk-grid-column-full">
        {% if not caption %}
            <h1 class="govuk-heading-{{ size }}">{{ title }}</h1>
        {% endif %}
        {% if caption and above %}
            <span class="govuk-caption-{{ size }}">{{ caption }}</span>
            <h1 class="govuk-heading-{{ size }}">{{ title }}</h1>
        {% endif %}
        {% if caption and below %}
            <h1 class="govuk-heading-{{ size }} govuk-!-margin-bottom-0">{{ title }}</h1>
            <span class="govuk-caption-{{ size }} govuk-!-margin-bottom-9">{{ caption }}</span>
        {% endif %}
    </div>
</div>

apps/templates/partials/cookie_banner.html
{% load query_params %}

{% if not request.cookie_preferences_set and request.path != '/cookies/' %}
    <div class="app-cookie-banner js--cookie-banner">
        <div class="cookie-banner__buttons govuk-width-container">
            <div class="govuk-grid-row">
                <div class="govuk-grid-column-two-thirds">
                    <p class="app-cookie-banner__message">
                        <span class="govuk-heading-m">Tell us whether you accept cookies</span>

                    <p class="govuk-body">We use <a class="govuk-link" href="{% url 'core:cookies' %}">cookies to collect
                        information</a> about how you use {{ settings.SERVICE_NAME }}. <br/>
                        We use this information to make the website work as well as possible and improve government
                        services.</p>

                    </p>
                    <button class="govuk-button js-accept-cookie app-cookie-banner__button-fixed-desktop">Accept all cookies</button>
                    <a href="{% url 'core:cookies' %}" class="govuk-button app-cookie-banner__button-fixed-desktop">Set cookie preferences</a>
                </div>
            </div>
        </div>
        <div class="cookie-banner__confirmation govuk-width-container" tabindex="-1">
            <div class="govuk-grid-row">
                <div class="govuk-grid-column-full">
                    <p class="govuk-body govuk-!-margin-top-4">
                        You’ve accepted all cookies. You can
                        <a class="govuk-link" href="{% url 'core:cookies' %}" data-module="track-click" data-track-category="cookieBanner" data-track-action="Cookie banner settings clicked from confirmation">change
                            your cookie settings</a> at any time.
                        <a class="govuk-link hide-button" href="#">Hide</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endif %}

{% if request.cookie_preferences_set and not request.global_bar_seen %}
    <div id="cookie-banner">
        <div id="global-bar-seen" class="govuk-width-container" tabindex="-1">
            <p class="govuk-body" role="alert">You’ve set your cookie preferences. You can <a
                    class="govuk-link" href="{% url 'core:cookies' %}" data-module="track-click"
                    data-track-category="cookieBanner"
                    data-track-action="Cookie banner settings clicked from confirmation">change your cookie settings</a>
                at any time.</p>
            <a class="govuk-button" role="button" href="{% current_path %}">Hide</a>
        </div>
    </div>
{% endif %}

apps/templates/partials/feedback_banner.html
<div class="govuk-phase-banner govuk-width-container">
    <p class="govuk-phase-banner__content">
        <strong class="govuk-tag govuk-phase-banner__content__tag">
            beta
        </strong>
        <span class="govuk-phase-banner__text">
            This is a new service – your <a class="govuk-link" href="#">feedback</a> will help us to improve it.
        </span>
    </p>
</div>

apps/templates/partials/footer.html
<footer class="govuk-footer " role="contentinfo">
    <div class="govuk-width-container ">
        <div class="govuk-footer__meta">
            <div class="govuk-footer__meta-item govuk-footer__meta-item--grow">
                <h2 class="govuk-visually-hidden">Support links</h2>
                <ul class="govuk-footer__inline-list">
                    <li class="govuk-footer__inline-list-item">
                        <a class="govuk-footer__link" href="{% url 'feedback:splash' %}">
                            Feedback and issues
                        </a>
                    </li>
                    <li class="govuk-footer__inline-list-item">
                        <a class="govuk-footer__link" href="{% url 'core:disclaimer' %}">
                            Disclaimer
                        </a>
                    </li>
                    <li class="govuk-footer__inline-list-item">
                        <a class="govuk-footer__link" href="{% url 'core:accessibility' %}">
                            Accessibility statement
                        </a>
                    </li>
                    <li class="govuk-footer__inline-list-item">
                        <a class="govuk-footer__link" href="{% url 'core:cookies' %}">
                            Cookies
                        </a>
                    </li>
                    <li class="govuk-footer__inline-list-item">
                        <a class="govuk-footer__link" href="https://www.gov.uk/help/privacy-notice">
                            Privacy notice
                        </a>
                    </li>
                </ul>

                <svg aria-hidden="true" focusable="false" class="govuk-footer__licence-logo"
                     xmlns="http://www.w3.org/2000/svg" viewBox="0 0 483.2 195.7" height="17" width="41">
                    <path fill="currentColor"
                          d="M421.5 142.8V.1l-50.7 32.3v161.1h112.4v-50.7zm-122.3-9.6A47.12 47.12 0 0 1 221 97.8c0-26 21.1-47.1 47.1-47.1 16.7 0 31.4 8.7 39.7 21.8l42.7-27.2A97.63 97.63 0 0 0 268.1 0c-36.5 0-68.3 20.1-85.1 49.7A98 98 0 0 0 97.8 0C43.9 0 0 43.9 0 97.8s43.9 97.8 97.8 97.8c36.5 0 68.3-20.1 85.1-49.7a97.76 97.76 0 0 0 149.6 25.4l19.4 22.2h3v-87.8h-80l24.3 27.5zM97.8 145c-26 0-47.1-21.1-47.1-47.1s21.1-47.1 47.1-47.1 47.2 21 47.2 47S123.8 145 97.8 145"/>
                </svg>
                <span class="govuk-footer__licence-description">
                    All content is available under the
                    <a class="govuk-footer__link"
                       href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated
                </span>
            </div>
            <div class="govuk-footer__meta-item">
                <a class="govuk-footer__link govuk-footer__copyright-logo"
                   href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/">©
                    Crown copyright</a>
            </div>
        </div>
    </div>
</footer>

apps/templates/partials/header.html
{% load static %}
{% load webpack_static from webpack_loader %}

<header class="govuk-header" role="banner" data-module="govuk-header">
    <div class="govuk-header__container govuk-width-container">
        <div class="govuk-header__logo">
            <a href="#" class="govuk-header__link govuk-header__link--homepage">
                <span class="govuk-header__logotype">
                    <svg aria-hidden="true" focusable="false" class="govuk-header__logotype-crown"
                         xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 30" height="30" width="32">
                         <path d="M22.6 10.4c-1 .4-2-.1-2.4-1-.4-.9.1-2 1-2.4.9-.4 2 .1 2.4 1s-.1 2-1 2.4m-5.9 6.7c-.9.4-2-.1-2.4-1-.4-.9.1-2 1-2.4.9-.4 2 .1 2.4 1s-.1 2-1 2.4m10.8-3.7c-1 .4-2-.1-2.4-1-.4-.9.1-2 1-2.4.9-.4 2 .1 2.4 1s0 2-1 2.4m3.3 4.8c-1 .4-2-.1-2.4-1-.4-.9.1-2 1-2.4.9-.4 2 .1 2.4 1s-.1 2-1 2.4M17 4.7l2.3 1.2V2.5l-2.3.7-.2-.2.9-3h-3.4l.9 3-.2.2c-.1.1-2.3-.7-2.3-.7v3.4L15 4.7c.1.1.1.2.2.2l-1.3 4c-.1.2-.1.4-.1.6 0 1.1.8 2 1.9 2.2h.7c1-.2 1.9-1.1 1.9-2.1 0-.2 0-.4-.1-.6l-1.3-4c-.1-.2 0-.2.1-.3m-7.6 5.7c.9.4 2-.1 2.4-1 .4-.9-.1-2-1-2.4-.9-.4-2 .1-2.4 1s0 2 1 2.4m-5 3c.9.4 2-.1 2.4-1 .4-.9-.1-2-1-2.4-.9-.4-2 .1-2.4 1s.1 2 1 2.4m-3.2 4.8c.9.4 2-.1 2.4-1 .4-.9-.1-2-1-2.4-.9-.4-2 .1-2.4 1s0 2 1 2.4m14.8 11c4.4 0 8.6.3 12.3.8 1.1-4.5 2.4-7 3.7-8.8l-2.5-.9c.2 1.3.3 1.9 0 2.7-.4-.4-.8-1.1-1.1-2.3l-1.2 4c.7-.5 1.3-.8 2-.9-1.1 2.5-2.6 3.1-3.5 3-1.1-.2-1.7-1.2-1.5-2.1.3-1.2 1.5-1.5 2.1-.1 1.1-2.3-.8-3-2-2.3 1.9-1.9 2.1-3.5.6-5.6-2.1 1.6-2.1 3.2-1.2 5.5-1.2-1.4-3.2-.6-2.5 1.6.9-1.4 2.1-.5 1.9.8-.2 1.1-1.7 2.1-3.5 1.9-2.7-.2-2.9-2.1-2.9-3.6.7-.1 1.9.5 2.9 1.9l.4-4.3c-1.1 1.1-2.1 1.4-3.2 1.4.4-1.2 2.1-3 2.1-3h-5.4s1.7 1.9 2.1 3c-1.1 0-2.1-.2-3.2-1.4l.4 4.3c1-1.4 2.2-2 2.9-1.9-.1 1.5-.2 3.4-2.9 3.6-1.9.2-3.4-.8-3.5-1.9-.2-1.3 1-2.2 1.9-.8.7-2.3-1.2-3-2.5-1.6.9-2.2.9-3.9-1.2-5.5-1.5 2-1.3 3.7.6 5.6-1.2-.7-3.1 0-2 2.3.6-1.4 1.8-1.1 2.1.1.2.9-.3 1.9-1.5 2.1-.9.2-2.4-.5-3.5-3 .6 0 1.2.3 2 .9l-1.2-4c-.3 1.1-.7 1.9-1.1 2.3-.3-.8-.2-1.4 0-2.7l-2.9.9C1.3 23 2.6 25.5 3.7 30c3.7-.5 7.9-.8 12.3-.8" fill="currentColor" fill-rule="evenodd"></path>
                        <image src="{% webpack_static 'govuk-public/images/govuk-logotype-tudor-crown.png' %}" xlink:href=""
                               class="govuk-header__logotype-crown-fallback-image" width="36" height="32"></image>
                    </svg>
                    <span class="govuk-header__logotype-text">GOV.UK</span>
                </span>
            </a>
        </div>
        <div class="govuk-header__content">
            <a href="{% url 'barriers:find-barriers-splash' %}" class="govuk-header__link govuk-header__link--service-name">
                {{ settings.SERVICE_NAME }}
            </a>
        </div>
    </div>
</header>