apps/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import CookiePolicyView, CookiesView

app_name = "core"

urlpatterns = [
    path("cookies/", CookiesView.as_view(), name="cookies"),
    path("cookie-policy/", CookiePolicyView.as_view(), name="cookie-policy"),
    path(
        "accessibility/",
        TemplateView.as_view(template_name="pages/accessibility.html"),
        name="accessibility",
    ),
    path(
        "disclaimer/",
        TemplateView.as_view(template_name="pages/disclaimer.html"),
        name="disclaimer",
    ),
]

apps/feedback/urls.py
from django.urls import path

from .views import (
    FeedbackBarrierView,
    FeedbackIssueView,
    FeedbackSplashView,
    FeedbackThankYouView,
    FeedbackUsabilityView,
)

app_name = "feedback"

urlpatterns = [
    path("feedback/", FeedbackSplashView.as_view(), name="splash"),
    path("feedback/barrier/", FeedbackBarrierView.as_view(), name="barrier"),
    path("feedback/issue/", FeedbackIssueView.as_view(), name="issue"),
    path("feedback/usability/", FeedbackUsabilityView.as_view(), name="usability"),
    path("feedback/thank-you/", FeedbackThankYouView.as_view(), name="thank-you"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from apps.pingdom.urls import urlpatterns as pingdom_urlpatterns

urlpatterns = []

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

    if settings.DJANGO_ENV == "local":
        urlpatterns += [
            path("admin/", admin.site.urls),
        ]

    # If debug toolbar is installed
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

    # Expose static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("", include("apps.barriers.urls", namespace="barriers")),
    path("", include("apps.core.urls", namespace="core")),
    path("", include("apps.feedback.urls", namespace="feedback")),
    path("", include("apps.healthcheck.urls", namespace="healthcheck")),
] + pingdom_urlpatterns

apps/templates/pages/accessibility.html
{% extends "base.html" %}

{% block page_title %}Accessibility statement - {{ block.super }}{% endblock %}

{% block page_content %}
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">

            <h1 class="govuk-heading-xl">Accessibility statement for Check international trade barriers</h1>
            <p class="govuk-body">This accessibility statement applies to Check International Trade Barriers service. It is part of the wider GOV.UK website which has a separate <a class="govuk-link" href="https://www.gov.uk/help/accessibility">accessibility statement</a>.</p>
            <p class="govuk-body">This service is run by the Department for Business and Trade (DBT). We want as many people as possible to be able to use this service. For example, that means you should be able to: </p>

            <ul class="govuk-list govuk-list--bullet">
                <li>change colours, contrast levels and fonts using browser or device settings</li>
                <li>zoom in up to 400% without the text spilling off the screen</li>
                <li>navigate most of the website using a keyboard or speech recognition software</li>
                <li>listen to most of the website using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li>
            </ul>
            <p class="govuk-body">We’ve also made the text in the service as simple as possible to understand.</p>
            <p class="govuk-body"><a class="govuk-link" href="https://mcmw.abilitynet.org.uk/">AbilityNet</a> has advice on making your device easier to use if you have a disability.</p>

            <h2 class="govuk-heading-l">Feedback and contact information</h2>
            <p class="govuk-body">If you need information on this website in a different format like accessible PDF, large print, easy read, audio recording or braille, email <a class="govuk-link" href="mailto:digitalmarketaccess@digital.trade.gov.uk">digitalmarketaccess@digital.trade.gov.uk</a>.</p>

            <h2 class="govuk-heading-l">Reporting accessibility problems with this service</h2>
            <p class="govuk-body">We’re always looking to improve the accessibility of this online service.</p>
            <p class="govuk-body">If you find any problems not listed on this page or think we’re not meeting the requirements of the accessibility regulations, contact: <a class="govuk-link" href="mailto:help@digital.trade.gov.uk">help@digital.trade.gov.uk</a> giving details of the issue and any assistive technology you are using.</p>

            <h2 class="govuk-heading-l">Enforcement procedure</h2>
            <p class="govuk-body">The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ‘accessibility regulations’). If you’re not happy with how we respond to your complaint, <a class="govuk-link" href="https://www.equalityadvisoryservice.com/">contact the Equality Advisory and Support Service (EASS)</a>.</p>

            <h2 class="govuk-heading-l">Technical information about this service’s accessibility</h2>

            <p class="govuk-body">DBT is committed to making this service accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.</p>

            <h2 class="govuk-heading-l">Compliance status</h2>

            <p class="govuk-body">The website has been tested against, and is fully compliant with, the <a class="govuk-link" href="https://www.w3.org/TR/WCAG22/">Web Content Accessibility Guidelines version 2.2</a> AA standard.</p>

            <h2 class="govuk-heading-l">How we tested this service</h2>
            <p class="govuk-body">The service was last tested on 18 September 2023 and was checked for compliance with WCAG 2.2 AA. The test was carried out by the Digital Accessibility Centre.</p>

            <h2 class="govuk-heading-l">Preparation of this accessibility statement</h2>
            <p class="govuk-body">This statement was prepared on 23 September 2020. It was last reviewed on 11 February 2025.</p>
            <p class="govuk-body">The service was last tested on 18 September 2023 and was checked for compliance with WCAG 2.2 AA. The test was carried out by the Digital Accessibility Centre.</p>
            <p class="govuk-body">DAC have a team of experienced auditors and analysts, many of whom are disabled individuals and users of adaptive technology.</p>
            <p class="govuk-body">The website was tested using a combination of pan-disability user feedback using a range of adaptive technologies and a technical audit using automated tools. The findings were combined to provide more accurate feedback. </p>
        </div>
    </div>
{% endblock %}

apps/templates/pages/cookie-policy.html
{% extends "base.html" %}
{% load breadcrumbs %}
{% load headers %}
{% load query_params %}

{% block page_title %}Cookie Details - {{ block.super }}{% endblock %}

{% block page_content %}
    <div class="govuk-grid-row cookie-preferences">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">Details about cookies on {{ settings.SERVICE_NAME }}</h1>
            <p class="govuk-body">{{ settings.SERVICE_NAME }} Service puts small files (known as ‘cookies’) onto your
                computer to collect information about how you browse the site and to enable the service to function
                efficiently and securely.</p>
            <p class="govuk-body">We use cookies to store information about how you use the {{ settings.SERVICE_NAME }}
                website, such as the
                pages you visit.</p>
            <p class="govuk-body">Cookies are used to:</p>
            <ul class="govuk-list govuk-list--bullet">
                <li>measure how you use the website so it can be updated and improved based on your needs</li>
                <li>assist in the function of your session when you register and log in to use the service and to manage
                    the
                    logging out from that service if your session is idle, protecting the security of any information
                    you
                    have entered
                </li>
                <li>manage the security of information you enter and files you upload</li>
            </ul>
            <p class="govuk-body">
                Find out more about <a href="https://ico.org.uk/for-the-public/online/cookies/">how to manage
                cookies</a>.
            </p>

            <h2 class="govuk-heading-l">How cookies are used on {{ settings.SERVICE_NAME }} Service</h2>
            <h3 class="govuk-heading-m">Measuring website usage (Google Analytics)</h3>
            <p class="govuk-body">We use Google Analytics software (Universal Analytics) to collect information about
                how
                you use {{ settings.SERVICE_NAME }} Service. We do this to help make sure the site is meeting the needs
                of
                its
                users and to help us make improvements, for example improving site search.</p>
            <p class="govuk-body">Google Analytics stores information about:</p>
            <ul class="govuk-list govuk-list--bullet">
                <li>the pages you visit on {{ settings.SERVICE_NAME }}</li>
                <li>how long you spend on each {{ settings.SERVICE_NAME }} Service page</li>
                <li>how you got to the site</li>
                <li>what you click on while you’re visiting the site</li>
            </ul>
            <p class="govuk-body">We do not collect or store your personal information (for example your name or
                address) so
                this information can’t be used to identify who you are.</p>
            <p class="govuk-body">{{ settings.SERVICE_NAME }} Service does not use Google Analytics after you have
                logged in
                to use the service.</p>
            <p class="govuk-body">We do not allow Google to use or share our analytics data.</p>

            <p class="govuk-body">Google Analytics sets the following cookies:</p>
            <table class="govuk-table">
                <thead class="govuk-table__head">
                <tr class="govuk-table__row">
                    <th scope="col" class="govuk-table__header">Name</th>
                    <th scope="col" class="govuk-table__header">Purpose</th>
                    <th scope="col" class="govuk-table__header">Expires</th>
                </tr>
                </thead>
                <tbody class="govuk-table__body">
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">_ga</th>
                    <td class="govuk-table__cell">
                        This helps us count how many people visit {{ settings.SERVICE_NAME }} by tracking if you’ve visited before
                    </td>
                    <td class="govuk-table__cell">
                        2 years
                    </td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">_gid</th>
                    <td class="govuk-table__cell">
                        This helps us count how many people visit {{ settings.SERVICE_NAME }} by tracking if you’ve visited before
                    </td>
                    <td class="govuk-table__cell">
                        24 hours
                    </td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">_gat</th>
                    <td class="govuk-table__cell">
                        Used to manage the rate at which page view requests are made
                    </td>
                    <td class="govuk-table__cell">
                        10 minutes
                    </td>
                </tr>
                </tbody>
                <p class="govuk-body">You can <a href="https://tools.google.com/dlpage/gaoptout">opt out of Google
                    Analytics
                    cookies</a>.</p>
            </table>

            <h3 class="govuk-heading-m">Checking the integrity of form submissions</h3>
            <p class="govuk-body">When you submit information through a form, a cookie is set to
                cross-reference data submitted by you against data received by the system.</p>
            <table class="govuk-table">
                <thead class="govuk-table__head">
                <tr class="govuk-table__row">
                    <th scope="col" class="govuk-table__header">Name</th>
                    <th scope="col" class="govuk-table__header">Purpose</th>
                    <th scope="col" class="govuk-table__header">Expires</th>
                </tr>
                </thead>
                <tbody class="govuk-table__body">
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">csrftoken</th>
                    <td class="govuk-table__cell">
                        Safeguards against cross site request forgery
                    </td>
                    <td class="govuk-table__cell">
                        Set with a future expiry date. Standard practice for this type of cookie.
                    </td>
                </tr>
                </tbody>
            </table>

            <h3 class="govuk-heading-m">Cookies message</h3>
            <p class="govuk-body">You may see a banner when you visit {{ settings.SERVICE_NAME }} Service inviting you to accept cookies or review
                your settings. We’ll set cookies so that your computer knows you’ve seen it and not to show it again,
                and also to store your settings.</p>
            <table class="govuk-table">
                <thead class="govuk-table__head">
                <tr class="govuk-table__row">
                    <th scope="col" class="govuk-table__header">Name</th>
                    <th scope="col" class="govuk-table__header">Purpose</th>
                    <th scope="col" class="govuk-table__header">Expires</th>
                </tr>
                </thead>
                <tbody class="govuk-table__body">
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">
                        {{ settings.COOKIE_SETTINGS_COOKIE_NAME }}
                    </th>
                    <td class="govuk-table__cell">
                        Saves your cookie consent settings
                    </td>
                    <td class="govuk-table__cell">
                        {{ settings.COOKIE_SETTINGS_EXPIRY }} days
                    </td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">
                        {{ settings.COOKIE_PREFERENCES_SET_COOKIE_NAME }}
                    </th>
                    <td class="govuk-table__cell">
                        Lets us know that you’ve saved your cookie consent settings
                    </td>
                    <td class="govuk-table__cell">
                        {{ settings.COOKIE_SETTINGS_EXPIRY }} days
                    </td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">
                        {{ settings.GLOBAL_BAR_SEEN_COOKIE_NAME }}
                    </th>
                    <td class="govuk-table__cell">
                        Remembers if you’ve seen the message about saving your cookie consent settings
                    </td>
                    <td class="govuk-table__cell">
                        {{ settings.COOKIE_SETTINGS_CONFIRMATION_BANNER }} days
                    </td>
                </tr>
                </tbody>
            </table>

            <h3 class="govuk-heading-m">Change your settings</h3>
            <p class="govuk-body">You can <a href="{% url 'core:cookies' %}{% next_filter %}" class="govuk-link">change which cookies you’re happy for us to use</a>.</p>

        </div>
    </div>

{% endblock %}

apps/templates/pages/cookies.html
{% extends "base.html" %}
{% load breadcrumbs %}
{% load headers %}
{% load query_params %}

{% block page_title %}Cookies - {{ block.super }}{% endblock %}

{% block page_content %}
    <div class="govuk-grid-row cookie-preferences">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">Cookies on {{ settings.SERVICE_NAME }}</h1>

            <form action="" method="POST">
                {% csrf_token %}
                <input type="hidden" name="redirect_url" value="{{ redirect_url }}">

                <p class="govuk-body">Cookies are files saved on your phone, tablet or computer when you visit a website.</p>
                <p class="govuk-body">We use cookies to store information about how you use the {{ settings.SERVICE_NAME }} website, such as the
                    pages you visit.</p>

                <h2 class="govuk-heading-l">Cookie settings</h2>
                <p class="govuk-body">We use two types of cookie. You can choose which cookies you're happy for us to use.</p>

                <div class="govuk-form-group" aria-describedby="ga-hint">
                    <fieldset class="govuk-fieldset">
                        <legend class="govuk-fieldset__legend govuk-fieldset__legend--m">
                            <h1 class="govuk-fieldset__heading">
                                Cookies that measure website use
                            </h1>
                        </legend>
                        <div id="ga-hint" class="govuk-hint">
                            <span>We use Google Analytics to measure how you use the website so we can improve it based on user needs. Google Analytics sets cookies that store anonymised information about:</span>
                            <ul class="govuk-list govuk-list--bullet">
                                <li>how you got to the site</li>
                                <li>the pages you visit on {{ settings.SERVICE_NAME }} and government digital services, and how long you spend on
                                    each page
                                </li>
                                <li>what you click on while you're visiting the site</li>
                            </ul>
                            <span>We do not allow Google to use or share the data about how you use this site.</span>
                        </div>
                        <div class="govuk-radios govuk-radios--inline">
                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" id="ga" name="{{ settings.GOOGLE_ANALYTICS_COOKIE_NAME }}" type="radio" value="True" {% if form.initial.usage == True %}checked{% endif %}>
                                <label class="govuk-label govuk-radios__label" for="ga">
                                  On
                                </label>
                            </div>
                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" id="ga-2" name="{{ settings.GOOGLE_ANALYTICS_COOKIE_NAME }}" type="radio" value="False" {% if form.initial.usage == False %}checked{% endif %}>
                                <label class="govuk-label govuk-radios__label" for="ga-2">
                                  Off
                                </label>
                            </div>
                        </div>
                    </fieldset>
                </div>

                <h3 class="govuk-heading-m">Strictly necessary cookies</h3>
                <p class="govuk-body">These essential cookies do things like remember your progress through a form.</p>
                <p class="govuk-body">They always need to be on.</p>
                <p class="govuk-body">
                    <a href="{% url 'core:cookie-policy' %}" class="govuk-link">Find out more about cookies on the {{ settings.SERVICE_NAME }} service</a>
                </p>
                <input type="submit" value="Save changes" class="govuk-button">
            </form>
        </div>
    </div>

{% endblock %}

apps/templates/pages/disclaimer.html
{% extends "base.html" %}

{% block page_title %}Disclaimer - {{ block.super }}{% endblock %}

{% block page_content %}
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-xl">Disclaimer</h1>

            <p class="govuk-body">
                The information in the ‘Check barriers to trading and investing abroad’ service is published under the
                Open Government License: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/.
            </p>

            <p class="govuk-body">
                The Department accepts no responsibility for the use or consequences of use of the data contained on
                this service by any third party.
            </p>

            <p class="govuk-body">
                This is an information only service and none of the information contained in this service should be
                taken to suggest that a business cannot or should not export to a particular country or market. The
                relative number of barriers in any given country or market should not be taken as an indication of the
                difficulty or ease in which that market can be accessed. The Department notes that there may be work
                arounds to barriers or alternative routes of entry and that users should make their own investigations
                when making decisions about their own activities.
            </p>

            <p class="govuk-body">
                None of the information contained in this service forms part of any official documents and is not
                intended to provide financial or legal advice. Some of the information being shared has been provided by
                UK businesses. Care has been taken to ensure the accuracy of the information contained within the
                service, but the Department for Business and Trade accepts no responsibility or liability for any
                inadvertent errors or omissions.
            </p>

            <p class="govuk-body">
                The “Date Reported” field represents the date that a given barrier was incorporated onto the service
                internally and does not represent the date first reported by a third party or the date of publication
                onto this public service. The barriers reported herein represent barriers reported at the time of
                publication and may have been changed or removed prior to updates of this service. Publication of a
                barrier or barriers on this service is not an indication of whether the Department for Business and
                Trade intends to act to address particular barriers. No personal data will be published on this service.
            </p>

            <p class="govuk-body">
                By clicking proceed and viewing the data you are acknowledging this disclaimer and agreeing to these
                terms for use of the service.
            </p>

            <h2 class="govuk-heading-m">What barriers are not included in the service</h2>
            <ul class="govuk-list govuk-list--bullet">
                <li>Barriers affecting imports into the United Kingdom</li>
                <li>Barriers which are sensitive for security reasons</li>
                <li>Barriers that identify a business even once individual details are removed due to niche/closed
                    nature of market
                </li>
                <li>Barriers which are politically sensitive</li>
                <li>Barriers for which insufficient/incomplete information is available</li>
                <li>Barriers which require further internal investigation</li>
            </ul>

            <p class="govuk-body">
                Please use the <a class="govuk-link" href="{% url "feedback:splash" %}">feedback</a> function to let us
                know of any issues or queries you have regarding this service.
            </p>

        </div>
    </div>
{% endblock %}